### ISSUE TITLE
我不开启nginx然后cloudflare SSL为flexible状态是ok的，但是nginx开了就不行，有什么思路吗？

### ISSUE THREAD

**Issue by S7venFeng** [jueinin/v2ray-websocket-nginx-cloudflare-CDN#1]
而且打开https://我的域名，是可以看到回显信息的。
三个配置文件包括证书安装都按照你的指导来的，不过之前用过Candy装过证书但是失败了。
请教下，谢谢。

**Comment by jueinin** [comment]
我不太理解哈,能详细说下嘛,只要https://域名没问题,开了cf代理也不应该出现问题啊

**Comment by S7venFeng** [comment]
解决了哈，是因为之前装的时候有些配置没删除导致的，顺便请教下，现在手机上能连上，但是电脑一直无法连接，如何配置多个用户？

**Comment by jueinin** [comment]
电脑无法连接的原因是什么呢,最好提供下配置文件和报错信息,是用的配置文件模板吗,配置多个用户在服务端文件里加用户即可,参考下文档

**Comment by y377** [comment]
大家好！

> 一个v2ray+websocket+nginx+cloudflare CDN的简单教程,大概是目前最安全的科学上网方式吧

敢问这个究竟是梯子还是CDN？难道你们当梯子用？那装一个openvpn直连有什么性能或者速度上的差异？
如果当梯子用，这招太费事了
